### ISSUE TITLE
Cannot launch on Fedora 32

### ISSUE THREAD

**Issue by corndog2000** [fract4d/gnofract4d#114]
I installed the program today from the Gnome store. When I went to run the program I got a notification saying that the program had crashed. Trying to run gnofract4d from the terminal prints out this error: https://pastebin.com/embed/7XeYBFv0

[Error in a text file](https://github.com/fract4d/gnofract4d/files/4685195/error.txt)

System information:
Python version: 3.8.2
OS: Fedora 32
Kernel: 5.6.14-300.fc32.x86_64

**Comment by mindhells** [comment]
As far as I know this issue (which I introduced btw) was fixed in #90 and its available on release [4.2](https://github.com/fract4d/gnofract4d/releases).
Not sure who, If anyone, is updating the Gnome store releases though.

**Comment by edyoung** [comment]
@corndog2000 can you provide a bit more info on where you downloaded from? Not familiar with the Gnome store.

**Comment by corndog2000** [comment]
> @corndog2000 can you provide a bit more info on where you downloaded from? Not familiar with the Gnome store.

The Gnome store is the app store for the Gnome desktop environment on Linux.

**Comment by jamesjer** [comment]
I am the maintainer of the Fedora gnofract4d package, which should be what @corndog2000 got from the Gnome store.  I updated to version 4.2 on May 29, so that should be what everyone gets now.  I am currently trying to update to version 4.3, but am seeing segfaults.  I'll open a new issue about that.  You can probably close this issue.
