### ISSUE TITLE
Travis setup didn't follow when migrating to fract4d org

### ISSUE THREAD

**Issue by edyoung** [fract4d/gnofract4d#92]
Travis isn't running any more. Anyone know how to fix it?

**Comment by DX-MON** [comment]
Under https://travis-ci.org/account/repositories you should see "MISSING AN ORGANIZATION?" with a link to review/add orgs, which should allow you to add the fract4d org to your account's authorisations, and re-enable the build.

**Comment by edyoung** [comment]
Thanks. Approved that but not 100% sure what else I need to do to get it working. (I didn't set it up initially).

**Comment by DX-MON** [comment]
I don't see it on my account, but in theory, it should have made it show up on yours if you use that repositories link again.

Click the Sync Account button on the left, then in the search box once it finishes sync'ing, pop 'fract4d' into the box and toggle the slider to the on position.

**Comment by DX-MON** [comment]
Quick question on the topic of tooling: We now have several branches left behind from merges, do you mind them being pruned? I figure the answer is 'do it' but that I'd also verify that

**Comment by mindhells** [comment]
@edyoung check https://github.com/settings/installations -> "travis CI", then grant access to the organization fract4d. Then you should be able to go to https://travis-ci.org/organizations/fract4d/repositories and enable this repository.
I had to do this for our fork (which we have it under our organization) because it stopped working for no reason... and it continues to fail to clone the repo from time to time.

**Comment by edyoung** [comment]
Appears to be at least partly working now: https://travis-ci.org/github/fract4d/gnofract4d/builds/687057774
